const actionTypes = {

 GET_POSTS_REQUEST : 'GET_POSTS_REQUEST',
 GET_POSTS_SUCCESS : 'GET_POSTS_SUCCESS',
 GET_POSTS_FAILURE : 'GET_POSTS_FAILURE',
 GET_POSTS_LIMIT_REQUEST : 'GET_POSTS_LIMIT_REQUEST',
 GET_POSTS_LIMIT_SUCCESS : 'GET_POSTS_LIMIT_SUCCESS',
 GET_POSTS_LIMIT_FAILURE : 'GET_POSTS_LIMIT_FAILURE',

}

export default actionTypes