const actionTypes = {

    GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
    GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
    GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',
    GET_POSTS_LIMIT_REQUEST: 'GET_POSTS_LIMIT_REQUEST',
    GET_POSTS_LIMIT_SUCCESS: 'GET_POSTS_LIMIT_SUCCESS',
    GET_POSTS_LIMIT_FAILURE: 'GET_POSTS_LIMIT_FAILURE',
    GET_NEW_POST: 'GET-NEW-POST',

    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',

    GET_CURRENT: 'GET_CURRENT'

}

export default actionTypes