name: Continuous Delivery to Render for Backend and Frontend

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Backend to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true
          wait_deploy: true
          github_deployment: true
          deployment_environment: 'production'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Frontend to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true
          wait_deploy: true
          github_deployment: true
          deployment_environment: 'production'
          github_token: ${{ secrets.GITHUB_TOKEN }}